---
## This playbook installs and configures AD authentication

- name: Final setting Ubuntu template
  user: sysadmin
  hosts: all
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:
    - name: Install chrony
      apt:
       name: chrony
       state: present
    - name: Set timezone to Asia/Ho_Chi_Minh
      community.general.timezone:
        name: Asia/Ho_Chi_Minh

    - name: Restart chronyd
      service:
        name: chronyd
        state: restarted
  
